base_url = "https://yugahirai.github.io/"
title = "Yuga Hirai : Quantum Computing Blog Posts"
description = "Yuga Hirai is a student at Keio Univ in Japan."
author = "Yuga Hirai"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
smart_punctuation = true

[markdown.highlighting]
enabled = true
theme = "dark-plus"
# More syntax highlighting themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting

[extra]
author = "Yuga Hirai"
email = "yuga917@keio.jp"
github = "https://github.com/yugahirai"
timeformat = "%B %e, %Y"                   # e.g. June 14, 2021

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a> and <a href="https://github.com/semanticdata/mabuya">Mabuya</a>.'
